FeedbackHub/urls.py
from django.urls import path
from .views import FeedbackHub

app_name = "FeedbackHub"

urlpatterns = [
    path('Comentarios/', FeedbackHub, name='quejas')
]

Simulador/urls.py
from django.urls import path
from .views import simulador

app_name = "Simulador"

urlpatterns = [
    path('Simulador/', simulador, name='Simulador')
]

creditos_uvr/urls.py
from django.contrib import admin
from django.urls import path, include
from UVRinfo.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='inicio'),
    path('FeedbackHub/', include('FeedbackHub.urls')),
    path('Simulador/', include('Simulador.urls')),
]

FeedbackHub/models.py
from django.db import models

# Create your models here.
class TipoMensaje(models.Model):
    tipo = models.CharField(max_length=11, unique=True)

class Usuario(models.Model):
    nombre = models.CharField(max_length=150)
    correo_electronico = models.EmailField(unique=True)
    
    class Meta:
        unique_together = [['nombre', 'correo_electronico']]

class Mensaje(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    tipo = models.ForeignKey(TipoMensaje, on_delete=models.CASCADE)
    asunto = models.CharField(max_length=250)
    contenido = models.TextField()
    fecha = models.DateField(auto_now=True)
    hora = models.TimeField(auto_now=True)

Simulador/models.py
from django.db import models

# Create your models here.

UVRinfo/models.py
from django.db import models

# Create your models here.

FeedbackHub/forms.py
from django import forms

class MensajeForm(forms.Form):
    nombre = forms.CharField(label='Nombre', max_length=100)
    email = forms.EmailField(label='Email', max_length=100)
    tipo = forms.ChoiceField(label='Tipo de mensaje', choices=[('Queja', 'Queja'), ('Sugerencia', 'Sugerencia'), ('Reclamo', 'Reclamo')])
    asunto = forms.CharField(label='Asunto', max_length=100)
    contenido = forms.CharField(label='Contenido', widget=forms.Textarea)

Simulador/forms.py
from django import forms

class SimuladorForm(forms.Form):
    monto_credito = forms.FloatField(label='Monto del crédito')
    tasa_anual = forms.FloatField(label='Tasa de interés anual')
    plazo_credito = forms.IntegerField(label='Plazo del crédito (en meses)')
    mes_pago = forms.IntegerField(label='Numero de cuota (ejemplo: 2 si es la segunda cuota que va a pagar)')

FeedbackHub/views.py
from .models import Usuario, Mensaje, TipoMensaje
from django.shortcuts import render
from .forms import MensajeForm

# Create your views here.
def create_user(data):
    try:
        nuevo_nombre = data.get('nombre')
        nuevo_email = data.get('email')
        
        # Verificar si ya existe un usuario con el mismo correo electrónico
        usuario_existente = Usuario.objects.filter(correo_electronico=nuevo_email).first()
        if usuario_existente:
            # Si el usuario ya existe, simplemente lo devuelve
            return usuario_existente, False
        
        # Si no existe, se crea uno nuevo
        nuevo_usuario = Usuario.objects.create(nombre=nuevo_nombre, correo_electronico=nuevo_email)
        return nuevo_usuario, True
    
    except Exception as e:
        print(e)
        return False

def create_mensaje(mensaje):
    try:
        data = mensaje
        
        # Crear o obtener el usuario
        nuevo_usuario, creado = create_user(data)
        
        print(f"tipo: {data.get('tipo')}")
        print(f"asunto: {data.get('asunto')}")
        print(f"contenido: {data.get('contenido')}")
        
        # Obtener el tipo de mensaje
        tipo_mensaje = TipoMensaje.objects.get(tipo=data.get('tipo'))
        
        # Crear el mensaje
        nuevo_mensaje = Mensaje.objects.create(
            usuario=nuevo_usuario,
            tipo=tipo_mensaje,
            asunto=data.get('asunto'),
            contenido=data.get('contenido')
        )
        
        return True  # Indica que el mensaje se creó correctamente
    
    except Exception as e:
        print(e)
        return False  # Indica que hubo un error al crear el mensaje

def FeedbackHub(request):
    form = MensajeForm()
    mensaje_aviso = None
    
    if request.method == 'POST':
        form = MensajeForm(request.POST)
        if form.is_valid():
            mensaje = request.POST
            if create_mensaje(mensaje):
                mensaje_aviso = True
            else:
                mensaje_aviso = False
    
    return render(request, 'Comentarios.html', {'form': form, 'mensaje_aviso': mensaje_aviso})
        
        

Simulador/views.py
from django.shortcuts import render
from .forms import SimuladorForm

# Create your views here.
# Calcula el valor de la cuota mensual del crédito UVR.
def calcular_cuota(monto_credito, tasa_anual, plazo_credito, mes_pago):
    # Lista para almacenar los detalles de cada mes
    pagos_data = []
    # Interes mensual
    r = (tasa_anual / 12) / 100
    #print(f'r: {r}')
    # Monto total del credito
    pv = monto_credito
    #print(f'pv: {pv}')
    # Numero total de pagos
    n = plazo_credito
    #print(f'n: {n}')
    # Tasa de inflacion mensual
    i = 0.01
    # Numero de la cuota
    m = mes_pago
    #print(f'm: {m}')
    
    saldo = pv
    
    pagos_data.append({
        'Mes': 0,
        'Cuota': 0,
        'Intereses': 0,
        'Inflacion': 0,
        'Abono': 0,
        'Saldo': monto_credito
    })
    
    for x in range(1, n+1):
        cuota_mensual = round(((r * pv) / (1 - (1 + r) ** -n)) * (1 + i) ** (x - 1), 3)
        # La cantidad de intereses que se pagan en la cuota
        intereses = round(saldo * r, 3)
        # La cantidad de inflacion que se paga en la cuota
        inflacion = round(cuota_mensual - (cuota_mensual / ((i + 1) ** (x - 1))), 3)
        #print(f'inflacion: {inflacion}')
        # La cantidad de dinero real que se va a pagar el saldo del prestamo
        abono = round(cuota_mensual - (intereses + inflacion), 3)
        
        saldo = round(saldo - abono, 4)
        
        if x == m:
            cuota_mes = cuota_mensual
        
        pagos_data.append({
            'Mes': x,
            'Cuota': cuota_mensual,
            'Intereses': intereses,
            'Inflacion': inflacion,
            'Abono': abono,
            'Saldo': saldo
        })
    
    #print(f'Cuota: {cuota_mes}')
    
    return cuota_mes, pagos_data

def simulador(request):
    if request.method == 'POST':
        form = SimuladorForm(request.POST)
        if form.is_valid():
            # Monto del crédito en pesos colombianos.
            monto_credito = float(request.POST.get('monto_credito'))
            # Tasa de interés UVR mensual.
            tasa_anual = float(request.POST.get('tasa_anual'))
            # Plazo del crédito en meses.
            plazo_credito = int(request.POST.get('plazo_credito'))
            # Periodicidad de los pagos (mensual).
            mes_pago = int(request.POST.get('mes_pago'))

            cuota_mes, pagos_data = calcular_cuota(monto_credito, tasa_anual, plazo_credito, mes_pago)

            context = {
                'form': form,
                'cuota_mes': cuota_mes,
                'numero_mes': mes_pago,
                'pagos_data': pagos_data,
            }
            
            return render(request, 'simulador.html', context)
    else:
        form = SimuladorForm()
    return render(request, 'simulador.html', {'form': form})

UVRinfo/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

FeedbackHub/templates/Comentarios.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />
        <link rel="stylesheet" href="{% static 'styles/form.css' %}" />
        <link rel="stylesheet" href="{% static 'styles/informe.css' %}" />
        <title>Comentarios</title>
    </head>
    <body>
        <header class="header">
            {% include 'components/main-navbar.html' %}
        </header>
        <div class="main-wrapper">
            {% include 'components/section-secondary.html' %}
            <main>
                <article>
                    <h1>Quejas, Reclamos y Sugerencias</h1>
                    <form method="POST" class="form-simulador">
                        {% csrf_token %} {{ form.as_p }}
                        <button type="submit">Enviar</button>
                    </form>

                    {% if mensaje_aviso == True %}
                    <div class="alerta correcto mostrar">
                        El mensaje se ha creado correctamente
                    </div>
                    {% elif mensaje_aviso == False %}
                    <div class="alerta incorrecto mostrar">
                        Hubo un error al crear el mensaje
                    </div>
                    {% endif %}
                </article>
            </main>
        </div>
    </body>
    <script>
        // Selecciona todas las alertas
        var alertas = document.querySelectorAll(".alerta");

        // Agrega la clase "mostrar" a cada alerta
        alertas.forEach(function (alerta) {
            alerta.classList.add("mostrar");
        });
    </script>
</html>

Simulador/templates/simulador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />
        <link rel="stylesheet" href="{% static 'styles/form.css' %}" />
        <title>Simulador de creditos UVR</title>
    </head>
    <body>
        <header class="header">
            {% include 'components/main-navbar.html' %}
        </header>
        <div class="main-wrapper">
            {% include 'components/section-secondary.html' %}
            <main>
                <article class="article-simulador">
                    <h1>Simulador de Creditos UVR</h1>

                    <div class="container">
                        <form class="form-simulador" method="POST">
                            {% csrf_token %} {{ form.as_p }}
                            <button type="submit">Calcular</button>
                        </form>
                    </div>

                    {% if cuota_mes %}
                    <p>
                        Esta simulación se basa en una inflación mensual
                        constante del 1%. Sin embargo, es importante tener en
                        cuenta que en la realidad, los valores pueden variar
                        considerablemente en un préstamo real. Esta herramienta
                        está diseñada para proporcionar una estimación de los
                        pagos que podrían enfrentar al utilizar un préstamo con
                        créditos UVR.
                    </p>

                    <h3 class="resultado">
                        Su cuota del mes {{ numero_mes }} es: ${{ cuota_mes }}
                    </h3>

                    <h2>Tabla de Pagos Mensuales</h2>

                    <table class="simulacion-casas cuotas">
                        <th class="title-table" colspan="6">
                            Simulacion de prestamo mes a mes
                        </th>
                        <tr>
                            <th>Mes</th>
                            <th>Cuota</th>
                            <th>Intereses</th>
                            <th>Inflacion</th>
                            <th>Abono</th>
                            <th>Saldo</th>
                        </tr>
                        {% for elem in pagos_data %}
                        <tr class="cuotas-row">
                            {% if elem.Mes == numero_mes %}
                            <td class="fila-cuota tabla-mes">{{ elem.Mes }}</td>
                            <td class="fila-cuota">{{ elem.Cuota }}</td>
                            <td class="fila-cuota">{{ elem.Intereses }}</td>
                            <td class="fila-cuota">{{ elem.Inflacion }}</td>
                            <td class="fila-cuota">{{ elem.Abono }}</td>
                            <td class="fila-cuota">{{ elem.Saldo }}</td>
                            {% else %}
                            <td class="tabla-mes">{{ elem.Mes }}</td>
                            <td>{{ elem.Cuota }}</td>
                            <td>{{ elem.Intereses }}</td>
                            <td>{{ elem.Inflacion }}</td>
                            <td>{{ elem.Abono }}</td>
                            <td>{{ elem.Saldo }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                    
                    <h3 class="alert">
                        Debido a múltiples redondeos, es posible que el saldo
                        final se aproxime a 0, pero no sea exactamente 0
                    </h3>
                    {% endif %}
                </article>
            </main>
        </div>
        {% include 'components/footer.html' %}
    </body>
</html>

UVRinfo/templates/components/footer.html
<footer>
    <p>Derechos de autor &copy; 2024 Ramón Felipe Pérez Osorio. Todos los derechos reservados.</p>
    <p>Contacto: rfperezos@unadvirtual.edu.co</p>
</footer>

UVRinfo/templates/components/main-navbar.html
<nav class="main-navbar">
    <ul>
        <li><a href="{% url 'inicio' %}">Home</a></li>
        <li><a href="{% url 'Simulador:Simulador' %}">Simulador</a></li>
        <li><a href="{% url 'FeedbackHub:quejas' %}">Comentarios</a></li>
    </ul>
</nav>

UVRinfo/templates/components/section-secondary.html
<aside class="section-secondary">
    <h2>Enlaces a otros sitios web sobre Creditos UVR</h2>
    <ul>
        <li>
            <a href="https://www.banrep.gov.co/es/estadisticas/unidad-valor-real-uvr">
                <p>https://www.banrep.gov.co/es/estadisticas/unidad-valor-real-uvr</p>
            </a>
        </li>
        <li>
            <a href="https://www.fna.gov.co/vivienda/caracteristicas-financieras/uvr">
                <p>https://www.fna.gov.co/vivienda/caracteristicas-financieras/uvr</p>
            </a>
        </li>
        <li>
            <a href="https://www.bbva.com.co/personas/blog/educacion-financiera/prestamos/uvr-o-pesos.html">
                <p>https://www.bbva.com.co/personas/blog/educacion-financiera/prestamos/uvr-o-pesos.html</p>
            </a>
        </li>
        <li>
            <a href="https://www.larepublica.co/finanzas-personales/se-vuelve-atractivo-volver-a-tomar-creditos-con-uvr-para-vivienda-ahora-que-cae-la-inflacion-3786688">
                <p>https://www.larepublica.co/finanzas-personales/se-vuelve-atractivo-volver-a-tomar-creditos-con-uvr-para-vivienda-ahora-que-cae-la-inflacion-3786688</p>
            </a>
        </li>
    </ul>
    <h2>Sitios web con asesoramiento gratuito</h2>
    <ul>
        <li>
            <a href="https://www.fna.gov.co/atencion-ciudadana/mis-canales/asesor-en-linea">
                <p>https://www.fna.gov.co/atencion-ciudadana/mis-canales/asesor-en-linea</p>
            </a>
        </li>
        <li>
            <a href="https://www.superfinanciera.gov.co/">
                <p>https://www.superfinanciera.gov.co/</p>
            </a>
        </li>
        <li>
            <a href="https://www.minhacienda.gov.co/">
                <p>https://www.minhacienda.gov.co/</p>
            </a>
        </li>
        <li>
            <a href="https://finanzasconproposito.org/">
                <p>https://finanzasconproposito.org/</p>
            </a>
        </li>
    </ul>
    <h2>Sitios fisicos con asesoramiento gratuito</h2>
    <ul>
        <li>
            <a href="https://www.superfinanciera.gov.co/#:~:text=Direcci%C3%B3n%3A%C2%A0Calle%207%20No.%204%20%2D%2049%20Bogot%C3%A1%2C%20D.C.">
                <p>https://www.superfinanciera.gov.co/#:~:text=Direcci%C3%B3n%3A%C2%A0Calle%207%20No.%204%20%2D%2049%20Bogot%C3%A1%2C%20D.C.</p>
            </a>
        </li>
        <li>
            <a href="https://www.bancolombia.com/puntos-de-atencion">
                <p>https://www.bancolombia.com/puntos-de-atencion</p>
            </a>
        </li>
        <li>
            <a href="https://www.fna.gov.co/atencion-ciudadana/puntos-de-atencion#:~:text=Puntos%20de%20Atenci%C3%B3n%20al%20P%C3%BAblico">
                <p>https://www.fna.gov.co/atencion-ciudadana/puntos-de-atencion#:~:text=Puntos%20de%20Atenci%C3%B3n%20al%20P%C3%BAblico</p>
            </a>
        </li>
        <li>
            <a href="https://www.minhacienda.gov.co/webcenter/portal/AtencionMHCP/pages_canalesa#:~:text=ser%20consulta%20aqu%C3%AD-,Direcci%C3%B3n,-Carrera%208%20No">
                <p>https://www.minhacienda.gov.co/webcenter/portal/AtencionMHCP/pages_canalesa#:~:text=ser%20consulta%20aqu%C3%AD-,Direcci%C3%B3n,-Carrera%208%20No</p>
            </a>
        </li>
    </ul>
</aside>

UVRinfo/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <title>Inicio - Creditos UVR</title>
</head>
<body>
    <header class="header">
        {% include 'components/main-navbar.html' %}
    </header>
    <div class="main-wrapper">
        {% include 'components/section-secondary.html' %}
        
        <main>
            <article>
                <h1>Todo sobre los Creditos UVR</h1>
                <p>
                    Los créditos UVR utilizan la Unidad de Valor Real. Esta es una unidad en la que, por ejemplo, un crédito UVR está en 400 pesos y pide un préstamo de 10'000.000 de pesos. El préstamo que le hace el banco es de 25.000 créditos UVR, no en 10'000.000. Puede parecer lo mismo, pero en realidad no lo es, ya que con el tiempo cada crédito UVR puede llegar a costar más, debido a que están enlazados con la inflación del país. Esto genera la pregunta: ¿Entonces, si la inflación baja, los créditos UVR también bajan? La respuesta es no. Si la inflación baja, los créditos UVR suben un poco, y si la inflación sube, los créditos UVR suben aún más.
                </p>

                <img src="{% static 'images/OIG1.jpg' %}" alt="Casa con graficas detras de ella">

                <p>
                    Entonces, ¿por qué se siguen usando los créditos UVR? Bueno, esto se debe a que hay una ley que impide a los bancos prestar dinero que requiera una primera cuota mensual más alta que el 40% del sueldo del prestatario, en este caso, usted. Poniendo un ejemplo en el que usted gane un sueldo superior al mínimo de Colombia, como por ejemplo 3'500.000, la máxima cuota que usted puede obtener es de 1'400.000, ya que ese es el 40% de su sueldo. Si quisiera pedir un préstamo de 126'000.000 en pesos en cuota fija, y la tasa efectiva anual es de 14,49%, y lo pidiera al máximo plazo que son 30 años, su cuota mensual sería de 1'541.937,826. Eso significa que el banco no podría aprobarle el crédito, pero con un préstamo por medio de créditos UVR, en el que la tasa es de 7,22%, su primera cuota sería de 856.979,7338 y si esta cuota es mucho más baja, casi la mitad que la que se usa en pesos, pero esto es solo al principio ya que como dije al principio estas cuotas irán aumentando mensualmente.
                </p>

                <img src="{% static 'images/OIG3.jpg' %}" alt="Personas haciendo fila">

                <p>
                    Ya que mientras que las cuotas del préstamo en pesos contienen el valor del capital, los intereses y los seguros, el préstamo en créditos UVR contiene el valor del capital, los intereses, los seguros y además la corrección monetaria. Este último valor es el que se encarga de corregir y mantener el valor de la deuda frente a la desvalorización por culpa de la inflación. Esto protege a las entidades bancarias de perder el valor del dinero prestado con el paso del tiempo, pero también afecta a los prestatarios, ya que se supone que el sueldo de las personas debe subir conforme aumenta la inflación, pero en un país como Colombia hay sueldos que se mantienen como están, y el sueldo mínimo no aumenta lo suficiente como para hacer frente al aumento de la inflación. Y es también este valor el que puede permitirle una primera cuota de 856.979,7338 pero puede llevarlo a pagar una cuota de más de 30'503.083,22.
                </p>
                
                <img src="{% static 'images/OIG6.jpg' %}" alt="Personas discutiendo sobre finanzas">

                <p>Si pusiéramos un ejemplo del total que pagaría con cada préstamo convirtiéndolas en la casa que iba a comprar con el préstamo, sería el siguiente:</p>

                <table class="simulacion-casas">
                    <th class="title-table" colspan="3">Simulacion de prestamo con casas</th>
                    <tr>
                        <th>Plazos</th>
                        <th>Prestamo en pesos</th>
                        <th>Préstamo en Créditos UVR</th>
                    </tr>
                    <tr>
                        <td>20 años</td>
                        <td>2 Casas</td>
                        <td>2,59 Casas</td>
                    </tr>
                    <tr>
                        <td>30 años</td>
                        <td>2,6 Casas</td>
                        <td>3,86 Casas</td>
                    </tr>
                </table>

                <p>
                    Como puede observar en la tabla, con el préstamo en créditos UVR en solo 20 años pagaría casi lo mismo que en 30 años con el préstamo en pesos.
                </p>

                <img src="{% static 'images/OIG7.jpg' %}" alt="montañas de dinero">

                <p>
                    Ya para concluir, el préstamo en pesos le permite mantenerse con una cuota fija con el paso del tiempo. Si sube la inflación, usted sigue pagando lo mismo, mientras que si baja, usted puede hacer venta de cartera, lo que le permite ajustar su crédito a nuevas tasas de interés más bajas. Esto no significa que esté libre de errores, o que los créditos UVR nunca sean útiles, ya que como explicamos anteriormente, le permiten adquirir un préstamo en el cual no está disponible en pesos, pero para hacer que sea eficiente el uso de los créditos UVR, tendrá que asesorarse más profundamente para aprender estos métodos y encontrar cuál se adapta mejor a su caso.
                </p>

                <img src="{% static 'images/OIG8.jpg' %}" alt="Persona que se asesoro en finanzas">
            </article>
        </main>
    </div>
    {% include 'components/footer.html' %}
</body>
</html>